/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface AuthorityManagerInterface extends Interface {
    getFunction(nameOrSignature: "active" | "agent" | "allowedTargets" | "deposit" | "execute" | "getAllowedTargets" | "maxSpend" | "owner" | "reactivate" | "renounceOwnership" | "revoke" | "setTarget" | "setTargets" | "transferOwnership" | "updateAuthority"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuthorityConfigured" | "AuthorityRevoked" | "ExecutionAttempt" | "OwnershipTransferred" | "TargetPermissionSet"): EventFragment;

    encodeFunctionData(functionFragment: 'active', values?: undefined): string;
encodeFunctionData(functionFragment: 'agent', values?: undefined): string;
encodeFunctionData(functionFragment: 'allowedTargets', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'deposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'execute', values: [AddressLike, BigNumberish, BytesLike, string, BytesLike]): string;
encodeFunctionData(functionFragment: 'getAllowedTargets', values?: undefined): string;
encodeFunctionData(functionFragment: 'maxSpend', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'reactivate', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'revoke', values?: undefined): string;
encodeFunctionData(functionFragment: 'setTarget', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setTargets', values: [AddressLike[], boolean]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateAuthority', values: [AddressLike, BigNumberish, boolean]): string;

    decodeFunctionResult(functionFragment: 'active', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'agent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowedTargets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'execute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllowedTargets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxSpend', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reactivate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revoke', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTarget', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTargets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateAuthority', data: BytesLike): Result;
  }

  
    export namespace AuthorityConfiguredEvent {
      export type InputTuple = [owner: AddressLike, agent: AddressLike, maxSpend: BigNumberish, active: boolean];
      export type OutputTuple = [owner: string, agent: string, maxSpend: bigint, active: boolean];
      export interface OutputObject {owner: string, agent: string, maxSpend: bigint, active: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AuthorityRevokedEvent {
      export type InputTuple = [owner: AddressLike, agent: AddressLike];
      export type OutputTuple = [owner: string, agent: string];
      export interface OutputObject {owner: string, agent: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExecutionAttemptEvent {
      export type InputTuple = [agent: AddressLike, target: AddressLike, amount: BigNumberish, data: BytesLike, reason: string, executionRef: BytesLike, success: boolean, result: BytesLike];
      export type OutputTuple = [agent: string, target: string, amount: bigint, data: string, reason: string, executionRef: string, success: boolean, result: string];
      export interface OutputObject {agent: string, target: string, amount: bigint, data: string, reason: string, executionRef: string, success: boolean, result: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TargetPermissionSetEvent {
      export type InputTuple = [target: AddressLike, allowed: boolean];
      export type OutputTuple = [target: string, allowed: boolean];
      export interface OutputObject {target: string, allowed: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AuthorityManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): AuthorityManager;
    waitForDeployment(): Promise<this>;

    interface: AuthorityManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    active: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    agent: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    allowedTargets: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    execute: TypedContractMethod<
      [target: AddressLike, amount: BigNumberish, data: BytesLike, reason: string, executionRef: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    getAllowedTargets: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    maxSpend: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    reactivate: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    revoke: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setTarget: TypedContractMethod<
      [target: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setTargets: TypedContractMethod<
      [targets: AddressLike[], allowed: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateAuthority: TypedContractMethod<
      [newAgent: AddressLike, newMaxSpend: BigNumberish, newActive: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'active'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'agent'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'allowedTargets'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'execute'): TypedContractMethod<
      [target: AddressLike, amount: BigNumberish, data: BytesLike, reason: string, executionRef: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAllowedTargets'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'maxSpend'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'reactivate'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revoke'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTarget'): TypedContractMethod<
      [target: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTargets'): TypedContractMethod<
      [targets: AddressLike[], allowed: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateAuthority'): TypedContractMethod<
      [newAgent: AddressLike, newMaxSpend: BigNumberish, newActive: boolean, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AuthorityConfigured'): TypedContractEvent<AuthorityConfiguredEvent.InputTuple, AuthorityConfiguredEvent.OutputTuple, AuthorityConfiguredEvent.OutputObject>;
getEvent(key: 'AuthorityRevoked'): TypedContractEvent<AuthorityRevokedEvent.InputTuple, AuthorityRevokedEvent.OutputTuple, AuthorityRevokedEvent.OutputObject>;
getEvent(key: 'ExecutionAttempt'): TypedContractEvent<ExecutionAttemptEvent.InputTuple, ExecutionAttemptEvent.OutputTuple, ExecutionAttemptEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'TargetPermissionSet'): TypedContractEvent<TargetPermissionSetEvent.InputTuple, TargetPermissionSetEvent.OutputTuple, TargetPermissionSetEvent.OutputObject>;

    filters: {
      
      'AuthorityConfigured(address,address,uint256,bool)': TypedContractEvent<AuthorityConfiguredEvent.InputTuple, AuthorityConfiguredEvent.OutputTuple, AuthorityConfiguredEvent.OutputObject>;
      AuthorityConfigured: TypedContractEvent<AuthorityConfiguredEvent.InputTuple, AuthorityConfiguredEvent.OutputTuple, AuthorityConfiguredEvent.OutputObject>;
    

      'AuthorityRevoked(address,address)': TypedContractEvent<AuthorityRevokedEvent.InputTuple, AuthorityRevokedEvent.OutputTuple, AuthorityRevokedEvent.OutputObject>;
      AuthorityRevoked: TypedContractEvent<AuthorityRevokedEvent.InputTuple, AuthorityRevokedEvent.OutputTuple, AuthorityRevokedEvent.OutputObject>;
    

      'ExecutionAttempt(address,address,uint256,bytes,string,bytes32,bool,bytes)': TypedContractEvent<ExecutionAttemptEvent.InputTuple, ExecutionAttemptEvent.OutputTuple, ExecutionAttemptEvent.OutputObject>;
      ExecutionAttempt: TypedContractEvent<ExecutionAttemptEvent.InputTuple, ExecutionAttemptEvent.OutputTuple, ExecutionAttemptEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'TargetPermissionSet(address,bool)': TypedContractEvent<TargetPermissionSetEvent.InputTuple, TargetPermissionSetEvent.OutputTuple, TargetPermissionSetEvent.OutputObject>;
      TargetPermissionSet: TypedContractEvent<TargetPermissionSetEvent.InputTuple, TargetPermissionSetEvent.OutputTuple, TargetPermissionSetEvent.OutputObject>;
    
    };
  }